
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label1;
	private global::Gtk.Entry entry1;
	private global::Gtk.Label label2;
	private global::Gtk.ComboBox combobox1;
	private global::Gtk.Label label3;
	private global::Gtk.Entry entry2;
	private global::Gtk.Label label9;
	private global::Gtk.Label label10;
	private global::Gtk.SpinButton spin;
	private global::Gtk.Label label11;
	private global::Gtk.CheckButton cb1;
	private global::Gtk.Label label12;
	private global::Gtk.CheckButton cb2;
	private global::Gtk.Label label13;
	private global::Gtk.CheckButton cb3;
	private global::Gtk.RadioButton rb4;
	private global::Gtk.Label label8;
	private global::Gtk.RadioButton rb3;
	private global::Gtk.Label label7;
	private global::Gtk.RadioButton rb1;
	private global::Gtk.Label label5;
	private global::Gtk.Entry total;
	private global::Gtk.Label label16;
	private global::Gtk.Button button1;
	private global::Gtk.Calendar calendario;
	private global::Gtk.Label label15;
	private global::Gtk.Label label4;
	private global::Gtk.Label label6;
	private global::Gtk.RadioButton rb2;
	private global::Gtk.CheckButton cb4;
	private global::Gtk.Label label14;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w1.X = 17;
		w1.Y = 18;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.fixed1.Add (this.entry1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry1]));
		w2.X = 76;
		w2.Y = 12;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Grupo");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w3.X = 264;
		w3.Y = 18;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.combobox1 = global::Gtk.ComboBox.NewText ();
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("A"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("B"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("C"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("D"));
		this.combobox1.WidthRequest = 64;
		this.combobox1.Name = "combobox1";
		this.combobox1.Active = 3;
		this.fixed1.Add (this.combobox1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.combobox1]));
		w4.X = 313;
		w4.Y = 14;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Codigo");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w5.X = 403;
		w5.Y = 17;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.fixed1.Add (this.entry2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry2]));
		w6.X = 460;
		w6.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("2.- ¿Cuanto es 2+2?");
		this.fixed1.Add (this.label9);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label9]));
		w7.X = 22;
		w7.Y = 158;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("3.-¿Cuales son los paises de america?");
		this.fixed1.Add (this.label10);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label10]));
		w8.X = 14;
		w8.Y = 240;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spin = new global::Gtk.SpinButton (0D, 100D, 1D);
		this.spin.CanFocus = true;
		this.spin.Name = "spin";
		this.spin.Adjustment.PageIncrement = 10D;
		this.spin.ClimbRate = 1D;
		this.spin.Numeric = true;
		this.fixed1.Add (this.spin);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spin]));
		w9.X = 26;
		w9.Y = 189;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("a)");
		this.fixed1.Add (this.label11);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label11]));
		w10.X = 11;
		w10.Y = 281;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.cb1 = new global::Gtk.CheckButton ();
		this.cb1.CanFocus = true;
		this.cb1.Name = "cb1";
		this.cb1.Label = global::Mono.Unix.Catalog.GetString ("Mexico");
		this.cb1.DrawIndicator = true;
		this.cb1.UseUnderline = true;
		this.fixed1.Add (this.cb1);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.cb1]));
		w11.X = 28;
		w11.Y = 278;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("b)");
		this.fixed1.Add (this.label12);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label12]));
		w12.X = 98;
		w12.Y = 280;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.cb2 = new global::Gtk.CheckButton ();
		this.cb2.CanFocus = true;
		this.cb2.Name = "cb2";
		this.cb2.Label = global::Mono.Unix.Catalog.GetString ("Peru");
		this.cb2.DrawIndicator = true;
		this.cb2.UseUnderline = true;
		this.fixed1.Add (this.cb2);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.cb2]));
		w13.X = 113;
		w13.Y = 277;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("c)");
		this.fixed1.Add (this.label13);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label13]));
		w14.X = 182;
		w14.Y = 279;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.cb3 = new global::Gtk.CheckButton ();
		this.cb3.CanFocus = true;
		this.cb3.Name = "cb3";
		this.cb3.Label = global::Mono.Unix.Catalog.GetString ("alemania");
		this.cb3.DrawIndicator = true;
		this.cb3.UseUnderline = true;
		this.fixed1.Add (this.cb3);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.cb3]));
		w15.X = 197;
		w15.Y = 276;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rb4 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("F"));
		this.rb4.CanFocus = true;
		this.rb4.Name = "rb4";
		this.rb4.DrawIndicator = true;
		this.rb4.UseUnderline = true;
		this.rb4.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.rb4);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.rb4]));
		w16.X = 293;
		w16.Y = 101;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("d)");
		this.fixed1.Add (this.label8);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label8]));
		w17.X = 274;
		w17.Y = 102;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rb3 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("I"));
		this.rb3.CanFocus = true;
		this.rb3.Name = "rb3";
		this.rb3.DrawIndicator = true;
		this.rb3.UseUnderline = true;
		this.rb3.Group = this.rb4.Group;
		this.fixed1.Add (this.rb3);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.rb3]));
		w18.X = 217;
		w18.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("c)");
		this.fixed1.Add (this.label7);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
		w19.X = 196;
		w19.Y = 101;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rb1 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("E"));
		this.rb1.CanFocus = true;
		this.rb1.Name = "rb1";
		this.rb1.DrawIndicator = true;
		this.rb1.UseUnderline = true;
		this.rb1.Group = this.rb4.Group;
		this.fixed1.Add (this.rb1);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.rb1]));
		w20.X = 59;
		w20.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("a)");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w21.X = 38;
		w21.Y = 101;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.total = new global::Gtk.Entry ();
		this.total.CanFocus = true;
		this.total.Name = "total";
		this.total.IsEditable = true;
		this.total.InvisibleChar = '●';
		this.fixed1.Add (this.total);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.total]));
		w22.X = 471;
		w22.Y = 356;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Puntos Totales");
		this.fixed1.Add (this.label16);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label16]));
		w23.X = 353;
		w23.Y = 361;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Terminar");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w24.X = 111;
		w24.Y = 355;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calendario = new global::Gtk.Calendar ();
		this.calendario.CanFocus = true;
		this.calendario.Name = "calendario";
		this.calendario.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add (this.calendario);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.calendario]));
		w25.X = 512;
		w25.Y = 151;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("4.- Cuando es dia del trabajo?");
		this.fixed1.Add (this.label15);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label15]));
		w26.X = 499;
		w26.Y = 109;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.Xalign = 1F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("1.- ¿Cuál es la tercera letra de abecedario?");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w27.X = 21;
		w27.Y = 64;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("b)");
		this.fixed1.Add (this.label6);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
		w28.X = 116;
		w28.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rb2 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("C"));
		this.rb2.CanFocus = true;
		this.rb2.Name = "rb2";
		this.rb2.DrawIndicator = true;
		this.rb2.UseUnderline = true;
		this.rb2.Group = this.rb4.Group;
		this.fixed1.Add (this.rb2);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.rb2]));
		w29.X = 136;
		w29.Y = 99;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.cb4 = new global::Gtk.CheckButton ();
		this.cb4.CanFocus = true;
		this.cb4.Name = "cb4";
		this.cb4.Label = global::Mono.Unix.Catalog.GetString ("Japon");
		this.cb4.DrawIndicator = true;
		this.cb4.UseUnderline = true;
		this.fixed1.Add (this.cb4);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.cb4]));
		w30.X = 326;
		w30.Y = 274;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("d)");
		this.fixed1.Add (this.label14);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label14]));
		w31.X = 303;
		w31.Y = 278;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 968;
		this.DefaultHeight = 443;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
	}
}
